"""Prewritten synthetic contracts for unknown display term buckets."""

import copy
import json
import unittest

from src.verify_treasury_auction_inventory import verify_archive

PDF = "https://www.treasurydirect.gov/instit/annceresult/press/preanre/"
DOCUMENT_KEYS = (
    "announcement_pdf",
    "competitive_pdf",
    "noncompetitive_pdf",
    "special_pdf",
    "announcement_xml",
    "competitive_xml",
)


def fixture():
    rows = [
        {
            "a": "AB1234567",
            "d": "9-Day",
            "z3a": "Bill",
            "t3a": "",
            "h": "2010-01-04",
            "i": "2010-01-05",
            "f3": "R_cmb.pdf",
        },
        {
            "a": "CD1234567",
            "d": "9-Year 11-Month",
            "z3a": "Note",
            "t3a": "10-Year",
            "h": "2010-01-05",
            "i": "2010-01-07",
            "f3": "R_note.pdf",
        },
        {
            "a": "AB1234567",
            "d": "13-Week",
            "z3a": "Bill",
            "t3a": "13-Week",
            "h": "2010-01-07",
            "i": "2010-01-11",
            "f3": "R_bill.pdf",
        },
    ]
    # Independently written expected records, not generated by a source projector.
    records = []
    for cusip, term, kind, bucket, announcement, auction, filename in (
        ("AB1234567", "9-Day", "Bill", "", "2010-01-04", "2010-01-05", "R_cmb.pdf"),
        (
            "CD1234567",
            "9-Year 11-Month",
            "Note",
            "10-Year",
            "2010-01-05",
            "2010-01-07",
            "R_note.pdf",
        ),
        ("AB1234567", "13-Week", "Bill", "13-Week", "2010-01-07", "2010-01-11", "R_bill.pdf"),
    ):
        documents = {key: [] for key in DOCUMENT_KEYS}
        documents["competitive_pdf"] = [PDF + "2010/" + filename]
        records.append(
            {
                "cusip": cusip,
                "security_term": term,
                "security_type": kind,
                "term_bucket": bucket,
                "announcement_date": announcement,
                "auction_date": auction,
                "documents": documents,
            }
        )
    return rows, records


def check(rows, records, start="2010-01-01", end="2010-12-31"):
    raw = rows if isinstance(rows, bytes) else json.dumps(rows).encode()
    return verify_archive(raw, records, start_date=start, end_date=end)


class VerifyTreasuryAuctionInventoryTests(unittest.TestCase):
    def test_three_record_cmb_note_bill_inventory_preserves_blank(self):
        rows, records = fixture()
        before = copy.deepcopy(records)
        for raw in (list(reversed(rows)), {"securityList": rows}):
            with self.subTest(wrapper=isinstance(raw, dict)):
                self.assertEqual(check(raw, records), {"status": "VERIFIED", "records": 3})
        self.assertEqual(records[0]["term_bucket"], "")
        self.assertEqual(records, before)
        with self.assertRaises(ValueError):
            check(rows, list(reversed(records)))

    def test_fabricated_bucket_or_other_metadata_is_rejected(self):
        rows, records = fixture()
        for assigned in ("CMB", "9-Day", "13-Week", None, 0, " "):
            wanted = copy.deepcopy(records)
            wanted[0]["term_bucket"] = assigned
            with self.subTest(assigned=assigned), self.assertRaises(ValueError):
                check(rows, wanted)
        for key in (
            "cusip",
            "security_type",
            "security_term",
            "announcement_date",
            "auction_date",
        ):
            wanted = copy.deepcopy(records)
            wanted[0][key] = "tampered"
            with self.subTest(key=key), self.assertRaises(ValueError):
                check(rows, wanted)

    def test_only_actual_exact_empty_bucket_is_permitted(self):
        rows, records = fixture()
        for bad in (None, 0, 123, True, False, [], {}, " ", "\t", "\n"):
            changed = copy.deepcopy(rows)
            changed[0]["t3a"] = bad
            with self.subTest(bucket=bad), self.assertRaises(ValueError):
                check(changed, records)
        changed = copy.deepcopy(rows)
        del changed[0]["t3a"]
        with self.assertRaises(ValueError):
            check(changed, records)
        for key in ("a", "d", "z3a", "h", "i"):
            for bad in ("", " ", None, 20100105, True):
                changed = copy.deepcopy(rows)
                changed[0][key] = bad
                with self.subTest(key=key, value=bad), self.assertRaises(ValueError):
                    check(changed, records)
        changed = copy.deepcopy(rows)
        changed[1]["t3a"] = " 10-Year "
        wanted = copy.deepcopy(records)
        wanted[1]["term_bucket"] = " 10-Year "
        self.assertEqual(check(changed, wanted)["records"], 3)

    def test_numeric_quarantine_duplicate_keys_and_json_envelopes(self):
        rows, records = fixture()
        token = json.dumps(rows[0])[:-1]
        huge = "8" * 7000
        raw = ("[" + token + ',"ignored":[' + huge + ",1e999999999,-1e-999999999]}]").encode()
        self.assertEqual(check(raw, records[:1])["records"], 1)
        invalid = [b"[]", b'{"securityList":[]}', b"\xff", b"null", b"callback([])"]
        invalid += [json.dumps({"securityList": rows, "extra": 1}).encode()]
        invalid += [
            ("[" + token + ',"ignored":' + value + "}]").encode()
            for value in ("NaN", "Infinity", "-Infinity")
        ]
        invalid += [("[" + token + ',"ignored":{"a":1,"a":2}}]').encode()]
        invalid += [json.dumps(rows).replace('"t3a": ""', '"t3a":"","t3a":""').encode()]
        for raw in invalid:
            with self.subTest(raw=raw[:50]), self.assertRaises(ValueError):
                check(raw, records)

    def test_dates_bounds_identity_and_preflight_before_filenames(self):
        rows, records = fixture()
        for bad in (
            "2010-02-30",
            "2010-1-5",
            "2010-01-05T01:00:00",
            "2010-01-05T00:00:00Z",
            "2010-01-05T00:00:00.000",
            "2011-01-01",
            "2009-12-31",
        ):
            changed = copy.deepcopy(rows)
            changed[0]["i"] = bad
            with self.subTest(date=bad), self.assertRaises(ValueError):
                check(changed, records)
        changed = copy.deepcopy(rows)
        changed[0]["h"] = "2010-01-06"
        with self.assertRaises(ValueError):
            check(changed, records)
        for start, end in (
            ("2009-01-01", "2010-12-31"),
            ("2010-01-01", "2025-10-21"),
            ("2010-12-31", "2010-01-01"),
            ("2010-01-01T00:00:00", "2010-12-31"),
        ):
            with self.subTest(start=start, end=end), self.assertRaises(ValueError):
                check(rows, records, start, end)
        with self.assertRaises(ValueError):
            check(rows + [copy.deepcopy(rows[0])], records)
        changed = copy.deepcopy(rows)
        changed[0]["f3"] = "../bad.pdf"
        changed[-1]["i"] = "2011-01-01"
        with self.assertRaisesRegex(ValueError, "[Dd]ate|[Bb]ound"):
            check(changed, records)

    def test_document_guards_and_all_six_exact_lists(self):
        rows, records = fixture()
        changed = copy.deepcopy(rows)
        changed[0].update(
            h="2009-12-31T00:00:00",
            i="2010-01-05T00:00:00",
            e3="A_name.PDF",
            e4="A_name.XML",
            ia1="R_name.xml",
            f31="N_name.pdf",
            f32="S_one.pdf, S_two.pdf",
        )
        wanted = copy.deepcopy(records)
        wanted[0]["announcement_date"] = "2009-12-31"
        wanted[0]["documents"].update(
            announcement_pdf=[PDF + "2009/A_name.PDF"],
            announcement_xml=["https://www.treasurydirect.gov/xml/A_name.XML"],
            competitive_xml=["https://www.treasurydirect.gov/xml/R_name.xml"],
            noncompetitive_pdf=[PDF + "2010/N_name.pdf"],
            special_pdf=[PDF + "2010/S_one.pdf", PDF + "2010/S_two.pdf"],
        )
        self.assertEqual(check(changed, wanted)["records"], 3)
        for value in (
            "../x.pdf",
            "x.pdf?q=1",
            "https://evil.example/x.pdf",
            "x\\y.pdf",
            "x.y.pdf",
            "x%2Fy.pdf",
            "x.xml",
            "x.pdf, y.pdf",
            "x.pdF\n",
            "x.KDF",
            [],
            0,
            " ",
        ):
            changed = copy.deepcopy(rows)
            changed[0]["f3"] = value
            with self.subTest(filename=value), self.assertRaises(ValueError):
                check(changed, records)
        for value in ("x.pdf,y.pdf", "x.pdf,  y.pdf", "x.pdf, "):
            changed = copy.deepcopy(rows)
            changed[0]["f32"] = value
            with self.subTest(special=value), self.assertRaises(ValueError):
                check(changed, records)

    def test_projection_schema_and_link_tampering(self):
        rows, records = fixture()
        for key in records[0]:
            wanted = copy.deepcopy(records)
            del wanted[0][key]
            with self.subTest(key=key), self.assertRaises(ValueError):
                check(rows, wanted)
        changes = []
        wanted = copy.deepcopy(records)
        wanted[0]["extra"] = 1
        changes.append(wanted)
        for value in (
            [],
            ["https://evil.example/R_cmb.pdf"],
            [PDF + "2011/R_cmb.pdf"],
            PDF + "2010/R_cmb.pdf",
        ):
            wanted = copy.deepcopy(records)
            wanted[0]["documents"]["competitive_pdf"] = value
            changes.append(wanted)
        for key in DOCUMENT_KEYS:
            wanted = copy.deepcopy(records)
            del wanted[0]["documents"][key]
            changes.append(wanted)
        wanted = copy.deepcopy(records)
        wanted[0]["documents"]["extra"] = []
        changes.append(wanted)
        for wanted in (records[:1], records + records[:1], *changes):
            with self.subTest(wanted=wanted), self.assertRaises(ValueError):
                check(rows, wanted)


if __name__ == "__main__":
    unittest.main()
