"""Post-result diagnostic: what the pooled ranking scoreboard actually measures.

ADDITIVE. This module reads only frozen artifacts, refits nothing, and rewrites
no verdict. `representation_study.yaml` registers a phase-mean AUC pooled across
24 annual folds, and `latent_k1_confirmation.yaml` registers a 99-control
randomization against that same statistic. Both stand. This measures a property
of the statistic that neither protocol anticipated.

THE PROBLEM. The folds are annual and the event is a five-session tail episode
at an annual 80th-percentile threshold, so the event RATE varies enormously
between folds -- 0.000 in 2004/2005/2006/2013 to 0.808 in 2022, sd 0.181. AUC
computed over the pooled rows counts every (event, non-event) pair, and the
overwhelming majority of those pairs straddle two different years. A score that
merely knows WHICH YEAR is volatile therefore scores well without being able to
rank one day against another day in the same year -- which is the thing a tail
forecaster has to do.

Quantified by a `fold-constant oracle`: assign every row its own fold's realized
event rate. It has ZERO within-year information by construction. It is also not
achievable -- it peeks at the fold's outcome -- so it is not a forecast, it is a
CEILING ON THE BETWEEN-FOLD COMPONENT of the registered statistic. The
prior-years-only version of the same score is included as the honest floor: it
sits at chance, which is the point. Knowing which year will be volatile is not
something any of these models can do either.

Reported alongside is the WITHIN-FOLD AUC: the same score, evaluated only on
pairs inside a single fold and phase, pair-count weighted. That is the part of
the registered statistic that is about the representation rather than about the
calendar.

  make pooling-diagnostic
"""
from __future__ import annotations

import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score

from . import config

DATA = "data/representation_study"
SCOREBOARD = {
    "tail_classical_forecasts.parquet": [
        ("p_benchmark", "RV-history ridge logistic (registered benchmark)"),
        ("p_rv_percentile", "trailing-RV percentile"),
        ("p_hmm_platt", "Platt-calibrated HMM state probability"),
        ("p_hmm_augmented", "benchmark + calibrated HMM"),
    ],
    "latent_k1_confirmation_forecasts.parquet": [
        ("p_latent_sparse_k1_99", "TiRex latent sparse k=1 (99-control rung)"),
    ],
}


def _phase_mean_auc(df: pd.DataFrame, score: pd.Series) -> float:
    """The registered primary statistic: unweighted mean over origin phases."""
    aucs = []
    for _, g in df.groupby("ranking_phase"):
        if g["event"].nunique() < 2:
            continue
        aucs.append(roc_auc_score(g["event"], score.loc[g.index]))
    return float(np.mean(aucs)) if aucs else float("nan")


def _within_fold_auc(df: pd.DataFrame, score: pd.Series) -> tuple[float, int]:
    """AUC restricted to pairs inside one fold and phase, pair-count weighted.

    Cells where the fold has no within-fold variation in `event` contribute
    nothing -- there is no pair to order -- so the four zero-event folds drop
    out here while still inflating the pooled statistic above.
    """
    rows = []
    for _, g in df.groupby(["ranking_phase", "fold_year"]):
        if g["event"].nunique() < 2:
            continue
        rows.append((len(g), roc_auc_score(g["event"], score.loc[g.index])))
    if not rows:
        return float("nan"), 0
    w = np.array([r[0] for r in rows], dtype=float)
    v = np.array([r[1] for r in rows], dtype=float)
    return float((w * v).sum() / w.sum()), len(rows)


def _oracles(df: pd.DataFrame) -> tuple[float, float]:
    realized = df.groupby("fold_year")["event"].transform("mean")
    years = sorted(df["fold_year"].unique())
    prior = {}
    for y in years:
        past = df[df["fold_year"] < y]["event"]
        prior[y] = float(past.mean()) if len(past) else 0.0
    return (_phase_mean_auc(df, realized),
            _phase_mean_auc(df, df["fold_year"].map(prior)))


def run() -> str:
    cfg = config.load()
    root = config.ROOT
    lines = ["# Pooling diagnostic — what the ranking scoreboard measures\n",
             "**Post-result, additive, refits nothing.** Generated by "
             "`src/pooling_diagnostic.py` from frozen forecast artifacts. The "
             "registered phase-mean AUC in `representation_study.yaml` and the "
             "99-control randomization in `latent_k1_confirmation.yaml` are "
             "unchanged and their verdicts stand. See "
             "`reports/AMENDMENTS.md`.\n"]

    for fname, models in SCOREBOARD.items():
        path = root / DATA / fname
        if not path.exists():
            continue
        df = pd.read_parquet(path)
        rates = df.groupby("fold_year")["event"].mean()
        oracle, prior_only = _oracles(df)
        lines.append(f"## `{fname}`\n")
        lines.append(
            f"{len(df):,} origins over {len(rates)} annual folds. Fold event "
            f"rate ranges **{rates.min():.3f} – {rates.max():.3f}** "
            f"(sd {rates.std():.3f}); "
            f"{int((rates == 0).sum())} folds contain no event at all. Most "
            f"(event, non-event) pairs in the pooled statistic therefore "
            f"straddle two different years.\n")
        lines.append("| score | registered phase-mean AUC | within-fold AUC | "
                     "beats the no-within-year-information ceiling? |")
        lines.append("|---|---|---|---|")
        for col, label in models:
            if col not in df.columns:
                continue
            pooled = _phase_mean_auc(df, df[col])
            wf, cells = _within_fold_auc(df, df[col])
            verdict = "**yes**" if pooled > oracle else "**no**"
            lines.append(f"| `{col}` — {label} | {pooled:.4f} | {wf:.4f} "
                         f"({cells} cells) | {verdict} |")
        lines.append(f"| *fold-constant oracle (zero within-year information)* "
                     f"| **{oracle:.4f}** | 0.5000 by construction | — |")
        lines.append(f"| *same, prior-folds only (no look-ahead)* "
                     f"| {prior_only:.4f} | — | — |\n")

    lines.append("## How to read this\n")
    lines.append(
        "The fold-constant oracle is **not a forecast** — it reads the fold's "
        "own realized event rate. It is a ceiling on how much of the "
        "registered statistic is available from between-fold variation alone. "
        "The prior-folds-only row shows that this information is not actually "
        "forecastable: it sits at chance. So a model scoring below the oracle "
        "is not thereby cheating; it is being measured by a statistic whose "
        "bulk is not about the thing the study is testing.\n")
    lines.append(
        "The within-fold column is the part that *is* about the "
        "representation: can this score rank one day above another day in the "
        "same year? Every score loses a great deal there, and the ordering is "
        "not preserved.\n")
    lines.append(
        "Nothing here refutes a registered verdict. It changes what the "
        "headline AUC numbers should be taken to mean, and it means a "
        "future ranking protocol should stratify within fold before "
        "comparing.\n")

    out = root / "reports" / "representation_study" / "pooling_diagnostic.md"
    out.write_text("\n".join(lines))
    return str(out)


if __name__ == "__main__":
    print(f"wrote {run()}")
